<?php

return [
    'subscription_ending' => ['label' => '⚠️ Fin d’abonnement', 'title' => 'Votre abonnement arrive à échéance', 'message' => 'Votre abonnement EduManager arrive bientôt à son terme. Renouvelez-le afin de conserver un accès continu à vos services.', 'icon' => 'fa-triangle-exclamation', 'category' => 'subscription', 'priority' => 'urgent'],
    'subscription_paid' => ['label' => '✅ Abonnement payé', 'title' => 'Paiement d’abonnement confirmé', 'message' => 'Votre paiement a bien été reçu. Votre abonnement EduManager est maintenant actif.', 'icon' => 'fa-calendar-check', 'category' => 'subscription', 'priority' => 'normal'],
    'software_update' => ['label' => '🚀 Mise à jour du logiciel', 'title' => 'Une mise à jour EduManager est disponible', 'message' => 'Une nouvelle mise à jour est disponible avec des améliorations de performance et de nouvelles fonctionnalités.', 'icon' => 'fa-arrows-rotate', 'category' => 'update', 'priority' => 'normal'],
    'school_year_ended' => ['label' => '📚 Année scolaire terminée', 'title' => 'Année scolaire terminée', 'message' => 'L’année scolaire est désormais terminée. Merci à toute la communauté éducative pour son engagement.', 'icon' => 'fa-graduation-cap', 'category' => 'school_year', 'priority' => 'normal'],
    'report_available' => ['label' => '📄 Bulletin disponible', 'title' => 'Votre bulletin est disponible', 'message' => 'Un nouveau bulletin est disponible dans votre espace EduManager.', 'icon' => 'fa-file-lines', 'category' => 'bulletin', 'priority' => 'normal'],
    'tuition_paid' => ['label' => '💳 Paiement de la scolarité', 'title' => 'Paiement de scolarité enregistré', 'message' => 'Un paiement de scolarité vient d’être enregistré. Consultez votre espace pour les détails.', 'icon' => 'fa-credit-card', 'category' => 'payment', 'priority' => 'normal'],
    'staff' => ['label' => '👨‍💼 Notification au personnel', 'title' => 'Information destinée au personnel', 'message' => 'Une information importante est communiquée à l’ensemble du personnel.', 'icon' => 'fa-users', 'category' => 'staff', 'priority' => 'normal'],
    'teachers' => ['label' => '👨‍🏫 Notification aux enseignants', 'title' => 'Information destinée aux enseignants', 'message' => 'Une information importante est communiquée à l’ensemble des enseignants.', 'icon' => 'fa-chalkboard-user', 'category' => 'teacher', 'priority' => 'normal'],
    'student_registered' => ['label' => '🎉 Nouvel élève inscrit', 'title' => 'Nouvel élève inscrit', 'message' => 'Un nouvel élève a été inscrit avec succès dans votre établissement.', 'icon' => 'fa-user-plus', 'category' => 'student', 'priority' => 'normal'],
    'establishment_created' => ['label' => '🏫 Nouvel établissement créé', 'title' => 'Nouvel établissement créé', 'message' => 'Un nouvel établissement a été créé avec succès dans EduManager.', 'icon' => 'fa-school', 'category' => 'establishment', 'priority' => 'normal'],
    'account_blocked' => ['label' => '🔒 Compte bloqué', 'title' => 'Votre compte a été bloqué', 'message' => 'Votre compte a été bloqué. Contactez l’administrateur pour plus d’informations.', 'icon' => 'fa-lock', 'category' => 'security', 'priority' => 'urgent'],
    'account_reactivated' => ['label' => '🔓 Compte réactivé', 'title' => 'Votre compte a été réactivé', 'message' => 'Votre compte a été réactivé. Vous pouvez à nouveau accéder à EduManager.', 'icon' => 'fa-lock-open', 'category' => 'security', 'priority' => 'normal'],
];
