@extends('client.layouts.app')
@section('title','Emploi du temps')
@section('content')
<div class="mb-6 flex items-center justify-between"><div><h2 class="text-2xl font-bold text-primary">Emploi du temps</h2><p class="text-sm text-text-muted">Planifiez les cours sans conflit de classe, salle ou enseignant.</p></div><div class="flex gap-2"><a target="_blank" href="{{ route('client.emploi-temps.print',['classe_id'=>$selectedClass]) }}" class="rounded-lg border px-4 py-2 text-sm">🖨️ Imprimer</a><a href="{{ route('client.emploi-temps.pdf',['classe_id'=>$selectedClass]) }}" class="rounded-lg bg-primary px-4 py-2 text-sm text-white">📥 Télécharger PDF</a></div></div>
<div class="mb-6 rounded-xl border bg-white p-5"><form method="POST" action="{{ route('client.emploi-temps.store') }}" class="grid gap-3 md:grid-cols-4">@csrf
<select name="etablissement_id" required class="rounded border p-2">@foreach($establishments as $e)<option value="{{ $e->id }}">{{ $e->nom }}</option>@endforeach</select><select name="annee_academique_id" required class="rounded border p-2">@foreach($years as $year)<option value="{{ $year->id }}">{{ $year->libelle }}</option>@endforeach</select>
<select name="classe_id" id="schedule-class" required class="rounded border p-2"><option value="">Classe</option>@foreach($classes as $class)<option value="{{ $class->id }}" @selected($selectedClass==$class->id)>{{ $class->nom }}</option>@endforeach</select><select name="jour" required class="rounded border p-2"><option value="lundi">Lundi</option><option value="mardi">Mardi</option><option value="mercredi">Mercredi</option><option value="jeudi">Jeudi</option><option value="vendredi">Vendredi</option><option value="samedi">Samedi</option></select>
<input name="heure_debut" type="time" required class="rounded border p-2"><input name="heure_fin" type="time" required class="rounded border p-2"><input name="salle" placeholder="Salle" class="rounded border p-2"><select name="matiere_id" required class="rounded border p-2"><option value="">Matière</option>@foreach($subjects as $s)<option value="{{ $s->id }}">{{ $s->nom }}</option>@endforeach</select><select name="enseignant_id" id="schedule-teacher" required class="rounded border p-2 md:col-span-3"><option value="">Choisissez d’abord une classe</option></select><button class="rounded bg-primary px-4 py-2 text-white">Ajouter le cours</button></form></div>
<div class="overflow-x-auto rounded-xl border bg-white"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-3">Horaire</th>@foreach(['lundi','mardi','mercredi','jeudi','vendredi','samedi'] as $day)<th class="p-3 capitalize">{{ $day }}</th>@endforeach</tr></thead><tbody>@foreach($entries->groupBy(fn($e)=>substr($e->heure_debut,0,5).'–'.substr($e->heure_fin,0,5)) as $time=>$rows)<tr class="border-t"><td class="p-3 font-semibold">{{ $time }}</td>@foreach(['lundi','mardi','mercredi','jeudi','vendredi','samedi'] as $day)@php($course=$rows->firstWhere('jour',$day))<td class="min-w-36 p-3">@if($course)<div class="rounded bg-indigo-50 p-2"><b>{{ $course->matiere->nom }}</b><br><span class="text-xs">{{ $course->enseignant->prenoms }} {{ $course->enseignant->nom }} · {{ $course->salle }}</span></div>@endif</td>@endforeach</tr>@endforeach</tbody></table></div>
@endsection
@push('scripts')<script>document.getElementById('schedule-class').addEventListener('change', e=>fetch(`{{ url('/client/emploi-temps/classes') }}/${e.target.value}/enseignants`).then(r=>r.json()).then(rows=>document.getElementById('schedule-teacher').innerHTML='<option value="">Enseignant</option>'+rows.map(t=>`<option value="${t.id}">${t.prenoms} ${t.nom}</option>`).join('')));</script>@endpush
